### ISSUE TITLE
Смысл модификатора

### ISSUE THREAD

**Issue by itgirlschool** [IrinaParamonova7980/VCS#21]
В чем смысл модификатора - у нас же нет других footer__menu

то есть можем модификатор внести в стили элемента)

https://github.com/IrinaParamonova7980/VCS/blob/792c9c44ebaa32f65567dac8c2419e0c73423857/Viarushka/page-1-viarushka.html#L46

**Comment by IrinaParamonova7980** [comment]
Есть footer__menu на другой странице, page-2-viarushka, там футер другого цвета.
