### ISSUE TITLE
Вынести значение шрифта в дефолтное/в отдельный класс

### ISSUE THREAD

**Issue by itgirlschool** [IrinaParamonova7980/VCS#23]
старайся избегать дублирования кода)

https://github.com/IrinaParamonova7980/VCS/blob/792c9c44ebaa32f65567dac8c2419e0c73423857/Viarushka/style-viarushka.css#L162

**Comment by IrinaParamonova7980** [comment]
Вынесла шрифт в body. Как вынести в отдельный класс, не нашла.
